export interface BankingActivity {
  activity_id: number;
  activity_type: { key: string; title: string };
  activity_name: string;
  account_name: string;
  transaction_date: string;
  amount: number;
}

export const bankingActivityList: BankingActivity[] = [
  {
    activity_id: 1,
    activity_type: { key: "atm-withdrawal", title: "ATM Withdrawal" },
    activity_name: "GTBank Victoria Island Branch",
    account_name: "Savings Account",
    transaction_date: "1676679806000",
    amount: -39151.54,
  },
  {
    activity_id: 2,
    activity_type: { key: "account-maintenance", title: "Account Maintenance" },
    activity_name: "Access Bank Marina Branch",
    account_name: "Current Account",
    transaction_date: "1656451035000",
    amount: -200.94,
  },
  {
    activity_id: 3,
    activity_type: { key: "cash-deposit", title: "Cash Deposit" },
    activity_name: "First Bank Lekki Branch",
    account_name: "Savings Account",
    transaction_date: "1663667631000",
    amount: 95900.04,
  },
  {
    activity_id: 4,
    activity_type: { key: "wire-transfer", title: "Wire Transfer" },
    activity_name: "GTBank Ikeja Branch",
    account_name: "Business Account",
    transaction_date: "1676113575000",
    amount: -7153943.03,
  },
  {
    activity_id: 5,
    activity_type: { key: "bill-payment", title: "Bill Payment" },
    activity_name: "Access Bank Marina Branch",
    account_name: "Current Account",
    transaction_date: "1664785957000",
    amount: -4500.00,
  },
  {
    activity_id: 6,
    activity_type: { key: "electronic-transfer", title: "Electronic Transfer" },
    activity_name: "GTBank Victoria Island Branch",
    account_name: "Savings Account",
    transaction_date: "1661293119000",
    amount: 2707627.22,
  },
  {
    activity_id: 7,
    activity_type: { key: "sms", title: "SMS Alert" },
    activity_name: "First Bank Lekki Branch",
    account_name: "Savings Account",
    transaction_date: "1659176714000",
    amount: -50.00,
  },
  {
    activity_id: 8,
    activity_type: { key: "card-transaction", title: "Card Transaction" },
    activity_name: "GTBank Ikeja Branch",
    account_name: "Debit Card",
    transaction_date: "1654261618000",
    amount: 15000.00,
  },
  {
    activity_id: 9,
    activity_type: { key: "atm-withdrawal", title: "ATM Withdrawal" },
    activity_name: "Access Bank Marina Branch",
    account_name: "Current Account",
    transaction_date: "1667845642000",
    amount: -25000.00,
  },
  {
    activity_id: 10,
    activity_type: { key: "account-maintenance", title: "Account Maintenance" },
    activity_name: "First Bank Lekki Branch",
    account_name: "Business Account",
    transaction_date: "1664676320000",
    amount: -350.00,
  },
  {
    activity_id: 11,
    activity_type: { key: "cash-deposit", title: "Cash Deposit" },
    activity_name: "GTBank Victoria Island Branch",
    account_name: "Savings Account",
    transaction_date: "1677244586000",
    amount: 500000.00,
  },
  {
    activity_id: 12,
    activity_type: { key: "wire-transfer", title: "Wire Transfer" },
    activity_name: "GTBank Ikeja Branch",
    account_name: "Current Account",
    transaction_date: "1668995276000",
    amount: -1285679.71,
  },
  {
    activity_id: 13,
    activity_type: { key: "electronic-transfer", title: "Electronic Transfer" },
    activity_name: "Access Bank Marina Branch",
    account_name: "Savings Account",
    transaction_date: "1666849808000",
    amount: 4097302.27,
  },
  {
    activity_id: 14,
    activity_type: { key: "bill-payment", title: "Bill Payment" },
    activity_name: "First Bank Lekki Branch",
    account_name: "Current Account",
    transaction_date: "1676487375000",
    amount: -8500.00,
  },
  {
    activity_id: 15,
    activity_type: { key: "card-transaction", title: "Card Transaction" },
    activity_name: "GTBank Victoria Island Branch",
    account_name: "Credit Card",
    transaction_date: "1658139648000",
    amount: -12500.00,
  },
  {
    activity_id: 16,
    activity_type: { key: "sms", title: "SMS Alert" },
    activity_name: "GTBank Ikeja Branch",
    account_name: "Savings Account",
    transaction_date: "1673601161000",
    amount: -25.00,
  },
  {
    activity_id: 17,
    activity_type: { key: "atm-withdrawal", title: "ATM Withdrawal" },
    activity_name: "Access Bank Marina Branch",
    account_name: "Savings Account",
    transaction_date: "1655904260000",
    amount: -15000.00,
  },
  {
    activity_id: 18,
    activity_type: { key: "account-maintenance", title: "Account Maintenance" },
    activity_name: "First Bank Lekki Branch",
    account_name: "Current Account",
    transaction_date: "1671277917000",
    amount: -200.00,
  },
  {
    activity_id: 19,
    activity_type: { key: "cash-deposit", title: "Cash Deposit" },
    activity_name: "GTBank Victoria Island Branch",
    account_name: "Business Account",
    transaction_date: "1665223252000",
    amount: 1000000.00,
  },
  {
    activity_id: 20,
    activity_type: { key: "wire-transfer", title: "Wire Transfer" },
    activity_name: "GTBank Ikeja Branch",
    account_name: "Savings Account",
    transaction_date: "1679665188000",
    amount: -2944191.69,
  },
  {
    activity_id: 21,
    activity_type: { key: "electronic-transfer", title: "Electronic Transfer" },
    activity_name: "Access Bank Marina Branch",
    account_name: "Current Account",
    transaction_date: "1668362657000",
    amount: 7512008.35,
  },
  {
    activity_id: 22,
    activity_type: { key: "bill-payment", title: "Bill Payment" },
    activity_name: "First Bank Lekki Branch",
    account_name: "Savings Account",
    transaction_date: "1671827265000",
    amount: -3200.00,
  },
  {
    activity_id: 23,
    activity_type: { key: "card-transaction", title: "Card Transaction" },
    activity_name: "GTBank Victoria Island Branch",
    account_name: "Debit Card",
    transaction_date: "1656699847000",
    amount: -8500.00,
  },
  {
    activity_id: 24,
    activity_type: { key: "atm-withdrawal", title: "ATM Withdrawal" },
    activity_name: "GTBank Ikeja Branch",
    account_name: "Current Account",
    transaction_date: "1656983867000",
    amount: -45000.00,
  },
  {
    activity_id: 25,
    activity_type: { key: "account-maintenance", title: "Account Maintenance" },
    activity_name: "Access Bank Marina Branch",
    account_name: "Business Account",
    transaction_date: "1654014513000",
    amount: -500.00,
  },
  {
    activity_id: 26,
    activity_type: { key: "sms", title: "SMS Alert" },
    activity_name: "First Bank Lekki Branch",
    account_name: "Savings Account",
    transaction_date: "1681166229000",
    amount: -30.00,
  },
  {
    activity_id: 27,
    activity_type: { key: "cash-deposit", title: "Cash Deposit" },
    activity_name: "GTBank Victoria Island Branch",
    account_name: "Savings Account",
    transaction_date: "1679758966000",
    amount: -25000.00,
  },
  {
    activity_id: 28,
    activity_type: { key: "wire-transfer", title: "Wire Transfer" },
    activity_name: "GTBank Ikeja Branch",
    account_name: "Current Account",
    transaction_date: "1682485534000",
    amount: -3856.44,
  },
  {
    activity_id: 29,
    activity_type: { key: "electronic-transfer", title: "Electronic Transfer" },
    activity_name: "Access Bank Marina Branch",
    account_name: "Savings Account",
    transaction_date: "1657344559000",
    amount: 2123.08,
  },
  {
    activity_id: 30,
    activity_type: { key: "bill-payment", title: "Bill Payment" },
    activity_name: "First Bank Lekki Branch",
    account_name: "Current Account",
    transaction_date: "1663711440000",
    amount: -7500.00,
  },
];
