import { baseNavigationObj } from "../baseNavigation";
import { NavigationTree } from "@/@types/navigation";

const ROOT_DASHBOARDS = "/dashboards";

const path = (root: string, item: string) => `${root}${item}`;

export const dashboards: NavigationTree = {
  ...baseNavigationObj["dashboards"],
  type: "root",
  childs: [
    {
      id: "dashboards.home",
      path: path(ROOT_DASHBOARDS, "/home"),
      type: "item",
      title: "Home",
      icon: "dashboards.sales",
    },
    {
      id: "dashboards.divide-1",
      type: "divider",
    },
    {
      id: "dashboards.sector",
      path: path(ROOT_DASHBOARDS, "/sector"),
      type: "collapse",
      title: "Sectors",
      icon: "dashboards.crm-analytics",
      childs: [
        {
          id: "dashboards.banks",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/sector/banks"),
          title: "Banks",
        },
        {
          id: "dashboards.hotels",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/sector/hotels"),
          title: "Hotels",
        },
        {
          id: "dashboards.power",
          path: path(ROOT_DASHBOARDS, "/sector/power"),
          type: "item",
          title: "Power",
        },
        {
          id: "dashboards.telecoms",
          path: path(ROOT_DASHBOARDS, "/sector/telecoms"),
          type: "item",
          title: "Telecoms",
        },
      ],
    },
    {
      id: "dashboards.regions",
      path: path(ROOT_DASHBOARDS, "/regions"),
      type: "collapse",
      title: "Regions",
      icon: "dashboards.cms-analytics",
      childs: [
        {
          id: "dashboards.regions.all",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions"),
          title: "All Regions",
        },
        {
          id: "dashboards.regions.abia",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/abia"),
          title: "Abia",
        },
        {
          id: "dashboards.regions.adamawa",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/adamawa"),
          title: "Adamawa",
        },
        {
          id: "dashboards.regions.akwa-ibom",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/akwa-ibom"),
          title: "Akwa Ibom",
        },
        {
          id: "dashboards.regions.anambra",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/anambra"),
          title: "Anambra",
        },
        {
          id: "dashboards.regions.bauchi",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/bauchi"),
          title: "Bauchi",
        },
        {
          id: "dashboards.regions.bayelsa",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/bayelsa"),
          title: "Bayelsa",
        },
        {
          id: "dashboards.regions.benue",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/benue"),
          title: "Benue",
        },
        {
          id: "dashboards.regions.borno",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/borno"),
          title: "Borno",
        },
        {
          id: "dashboards.regions.cross-river",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/cross-river"),
          title: "Cross River",
        },
        {
          id: "dashboards.regions.delta",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/delta"),
          title: "Delta",
        },
        {
          id: "dashboards.regions.ebonyi",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/ebonyi"),
          title: "Ebonyi",
        },
        {
          id: "dashboards.regions.edo",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/edo"),
          title: "Edo",
        },
        {
          id: "dashboards.regions.ekiti",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/ekiti"),
          title: "Ekiti",
        },
        {
          id: "dashboards.regions.enugu",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/enugu"),
          title: "Enugu",
        },
        {
          id: "dashboards.regions.gombe",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/gombe"),
          title: "Gombe",
        },
        {
          id: "dashboards.regions.imo",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/imo"),
          title: "Imo",
        },
        {
          id: "dashboards.regions.jigawa",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/jigawa"),
          title: "Jigawa",
        },
        {
          id: "dashboards.regions.kaduna",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/kaduna"),
          title: "Kaduna",
        },
        {
          id: "dashboards.regions.kano",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/kano"),
          title: "Kano",
        },
        {
          id: "dashboards.regions.katsina",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/katsina"),
          title: "Katsina",
        },
        {
          id: "dashboards.regions.kebbi",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/kebbi"),
          title: "Kebbi",
        },
        {
          id: "dashboards.regions.kogi",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/kogi"),
          title: "Kogi",
        },
        {
          id: "dashboards.regions.kwara",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/kwara"),
          title: "Kwara",
        },
        {
          id: "dashboards.regions.lagos",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/lagos"),
          title: "Lagos",
        },
        {
          id: "dashboards.regions.nasarawa",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/nasarawa"),
          title: "Nasarawa",
        },
        {
          id: "dashboards.regions.niger",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/niger"),
          title: "Niger",
        },
        {
          id: "dashboards.regions.ogun",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/ogun"),
          title: "Ogun",
        },
        {
          id: "dashboards.regions.ondo",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/ondo"),
          title: "Ondo",
        },
        {
          id: "dashboards.regions.osun",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/osun"),
          title: "Osun",
        },
        {
          id: "dashboards.regions.oyo",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/oyo"),
          title: "Oyo",
        },
        {
          id: "dashboards.regions.plateau",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/plateau"),
          title: "Plateau",
        },
        {
          id: "dashboards.regions.rivers",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/rivers"),
          title: "Rivers",
        },
        {
          id: "dashboards.regions.sokoto",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/sokoto"),
          title: "Sokoto",
        },
        {
          id: "dashboards.regions.taraba",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/taraba"),
          title: "Taraba",
        },
        {
          id: "dashboards.regions.yobe",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/yobe"),
          title: "Yobe",
        },
        {
          id: "dashboards.regions.zamfara",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/zamfara"),
          title: "Zamfara",
        },
        {
          id: "dashboards.regions.fct",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/regions/fct"),
          title: "FCT",
        },
      ],
    },
    {
      id: "dashboards.businesses",
      path: path(ROOT_DASHBOARDS, "/businesses"),
      type: "item",
      title: "Businesses",
      icon: "dashboards.influencer",
    },
    {
      id: "dashboards.branches",
      path: path(ROOT_DASHBOARDS, "/branches"),
      type: "item",
      title: "Branches",
      icon: "dashboards.travel",
    },
    // {
    //   id: "dashboards.education",
    //   path: path(ROOT_DASHBOARDS, "/education"),
    //   type: "item",
    //   title: "Education",
    //   transKey: "nav.dashboards.education",
    //   icon: "dashboards.education",
    // },
    // {
    //   id: "dashboards.authors",
    //   path: path(ROOT_DASHBOARDS, "/authors"),
    //   type: "item",
    //   title: "Authors",
    //   transKey: "nav.dashboards.authors",
    //   icon: "dashboards.authors",
    // },
    // {
    //   id: "dashboards.doctor",
    //   path: path(ROOT_DASHBOARDS, "/doctor"),
    //   type: "item",
    //   title: "Doctor",
    //   transKey: "nav.dashboards.doctor",
    //   icon: "dashboards.doctor",
    // },
    // {
    //   id: "dashboards.employees",
    //   path: path(ROOT_DASHBOARDS, "/employees"),
    //   type: "item",
    //   title: "Employees",
    //   transKey: "nav.dashboards.employees",
    //   icon: "dashboards.employees",
    // },
    // {
    //   id: "dashboards.workspaces",
    //   path: path(ROOT_DASHBOARDS, "/workspaces"),
    //   type: "item",
    //   title: "Workspaces",
    //   transKey: "nav.dashboards.workspaces",
    //   icon: "dashboards.workspaces",
    // },
    // {
    //   id: "dashboards.meetings",
    //   path: path(ROOT_DASHBOARDS, "/meetings"),
    //   type: "item",
    //   title: "Meetings",
    //   transKey: "nav.dashboards.meetings",
    //   icon: "dashboards.meetings",
    // },
    // {
    //   id: "dashboards.projects-board",
    //   path: path(ROOT_DASHBOARDS, "/projects-board"),
    //   type: "item",
    //   title: "Projects Board",
    //   transKey: "nav.dashboards.projects-board",
    //   icon: "dashboards.projects-board",
    // },
    // {
    //   id: "dashboards.divide-2",
    //   type: "divider",
    // },
    // {
    //   id: "dashboards.widget-ui",
    //   path: path(ROOT_DASHBOARDS, "/widget-ui"),
    //   type: "item",
    //   title: "Widgets UI",
    //   transKey: "nav.dashboards.widget-ui",
    //   icon: "dashboards.widget",
    // },
    // {
    //   id: "dashboards.widget-contact",
    //   path: path(ROOT_DASHBOARDS, "/widget-contact"),
    //   type: "item",
    //   title: "Widgets Contact",
    //   transKey: "nav.dashboards.widget-contact",
    //   icon: "dashboards.widget",
    // },
  ],
};
